# Generated by Django 3.1.2 on 2021-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
