# Generated by Django 3.1.6 on 2021-02-11 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0007_auto_20210211_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinputbill',
            name='output_bill',
        ),
        migrations.RemoveField(
            model_name='detailinputbill',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='detailinputbill',
            name='input_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_material.inputbill'),
        ),
        migrations.AddField(
            model_name='detailinputbill',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_material.product'),
        ),
        migrations.CreateModel(
            name='DetailOutputBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=10000)),
                ('output_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_material.outputbill')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_material.warehouse')),
            ],
        ),
    ]
