# Generated by Django 3.1.6 on 2021-03-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0009_auto_20210302_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinputbill',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detailoutputbill',
            name='price',
        ),
    ]
