# Generated by Django 3.1.6 on 2021-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0010_auto_20210302_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinputbill',
            name='price',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='detailoutputbill',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
