# Generated by Django 3.1.6 on 2021-03-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0013_auto_20210324_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='total_cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
