# Generated by Django 3.1.6 on 2021-03-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0014_shopping_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='buying_unit_cost',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
