# Generated by Django 3.1.6 on 2021-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_material', '0017_auto_20210401_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
