# Generated by Django 3.1.6 on 2021-02-09 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('unit_cost', models.IntegerField(default=1)),
                ('origin', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='vatlieu.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vatlieu.typeproduct'),
        ),
        migrations.CreateModel(
            name='InputBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_date', models.DateTimeField()),
                ('flag', models.IntegerField(choices=[(1, 'Pending'), (0, 'Out for delivery'), (-1, 'Delivered')], default=1)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bills', to='vatlieu.provider')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailInputBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1000)),
                ('input_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_input_bills', to='vatlieu.inputbill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_input_bills', to='vatlieu.product')),
            ],
        ),
    ]
