# Generated by Django 3.1.6 on 2021-02-11 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vatlieu', '0006_auto_20210210_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailinputbill',
            name='input_bill',
        ),
        migrations.RemoveField(
            model_name='detailinputbill',
            name='product',
        ),
        migrations.AddField(
            model_name='detailinputbill',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatlieu.warehouse'),
        ),
        migrations.CreateModel(
            name='OutputBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_date', models.DateTimeField()),
                ('flag', models.IntegerField(choices=[(1, 'Pending'), (0, 'Out for delivery'), (-1, 'Delivered')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_bills', to='vatlieu.customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detailinputbill',
            name='output_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatlieu.outputbill'),
        ),
    ]
