# Generated by Django 3.1.6 on 2021-03-24 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vatlieu', '0011_auto_20210302_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputbill',
            name='input_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='outputbill',
            name='output_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatlieu.product')),
            ],
        ),
    ]
