# Generated by Django 3.1.6 on 2021-03-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vatlieu', '0012_auto_20210324_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopping',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopping',
            name='flag',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Out for delivery'), (-1, 'Delivered')], default=1),
        ),
    ]
