# Generated by Django 3.1.6 on 2021-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatlieu', '0016_auto_20210331_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type_product__name']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['product__type_product__name']},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
