# Generated by Django 3.1.6 on 2021-04-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vatlieu', '0018_calculation_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calculationUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vatlieu.calculation_unit'),
        ),
    ]
